#! /bin/sh

set -ex

if [ "$#" -eq "1" ]; then
  AUTORECONF=$1
  echo "Using \`$1' instead of \`autoreconf' command"
else
  AUTORECONF=autoreconf
fi

sl-init-autoconf
$AUTORECONF -v -f -i

echo "Reconfiguration done."
